### ISSUE TITLE
Cloud-Init support

### ISSUE THREAD

**Issue by fabio-cogno** [89luca89/terrible#26]
Hi, does the terraform-libvirt template file support cloud init configuration?

I was using a cloud-init base image and the deploy is stuck on the task **TASK [terraform : Terraform apply VMs]**

**Comment by alegrey91** [comment]
Hi @fabio-cogno, actually we never tried to use a cloud-init image, so we are not sure these will work.
Usually we create our templates using Paker. The config files we used for that can be found here: https://github.com/89luca89/packer-terraform-kvm

**Comment by 89luca89** [comment]
@fabio-cogno , hi, we are adding cloud-init support to terrible in the next release
