### ISSUE TITLE
CI with basic infrastructure deployment

### ISSUE THREAD

**Issue by alegrey91** [89luca89/terrible#41]
As already mentioned in another thread (#40), this issue is dedicated to the evaluation of the implementation of a Github action to automate the deployment of basic infrastructure, using the following actions:
* https://github.com/marketplace/actions/packer-qemu-build
* https://github.com/marketplace/actions/docker-setup-qemu
* https://github.com/actions/checkout

A basic infrastructure means the ability to deploy one VM for each OS family supported (depending on the time it needs to do the job).

**Comment by alegrey91** [comment]
Seems that GitHub actions don't support hardware virtualization due to the use of Azure on [DV2](https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series) instances, as discussed on this thread: https://github.com/actions/virtual-environments/issues/183.
Luckily for us, perhaps, seems that Travis-CI do what we need.
Some examples:
* https://github.com/ankidroid/Anki-Android/blob/master/.travis.yml
* https://github.com/mmcc007/test_emulators/blob/master/.travis.yml

Another interesting thing, but out of topic, is this: https://hub.docker.com/r/ennweb/kvm

**Comment by 89luca89** [comment]
This should depend on #50 and use cloud_init images

**Comment by alegrey91** [comment]
To avoid the creation of each image using Packer, we decided to store the already built images on the cloud and download them from the Travis instance.
To do this, I've also found an interesting blog which explains how to do this: https://angelov.ai/post/2020/wget-files-from-gdrive/

**Comment by 89luca89** [comment]
@alegrey91 adding to this, we use those images instead of cloud-init images to ensure also support for all cases like luks setups (that are not always supported in cloud-init instances)

**Comment by alegrey91** [comment]
The pipeline seems to be ready. Today I'll do additional tests and then I think we could merge.
