### ISSUE TITLE
Create Dockerfile

### ISSUE THREAD

**Issue by alegrey91** [89luca89/terrible#51]
To avoid dependencies problems, we could provide a Dockerfile to allow the users to build the Terrible container by themself.
The container should include:
* Ansible
* Terraform
* Terraform Provider for Libvirt

And possibly also other things if necessary. The Travis pipeline could be inspirational for this issue.

**Comment by alegrey91** [comment]
Seems we need to chose between one of the following images for our container:
* Fedora
* OpenSuse
* Ubuntu
This is due to the **terraform-provider-libvirt** (https://github.com/dmacvicar/terraform-provider-libvirt/releases) which is compiled fro these OS.
Alternatively we could use Alpine, but we have to compile it by ourselves.
@89luca89

**Comment by 89luca89** [comment]
@alegrey91 works fine also centos8 and Debian

**Comment by alegrey91** [comment]
@89luca89 so I think the lightest one will be our choose.

**Comment by alegrey91** [comment]
Should we provide also a github action to test the Dockerfile?

**Comment by 89luca89** [comment]
That would be a whim

**Comment by alegrey91** [comment]
I've found this interesting link: https://github.com/marketplace/actions/build-and-push-docker-images
We could use this action to automatically deploy the container image to dockerhub when the build succeeded.

**Comment by 89luca89** [comment]
@alegrey91 nice work on the container

now what I would like to see, is that we set an entrypoint to

`ansible-playbook -u root main.yml -i $@`

this way, it can be used simply from external using

`docker run terrible my_inventory.yml` 

or


`docker run terrible my_inventory.yml --tags validate -vvv`  

thus not having to make mountpoints or entering the container itself to be used

**Comment by alegrey91** [comment]
Ok, seems to be a good idea. I'll push asap.
