### ISSUE TITLE
[IMPROVEMENT] Update Dockerfile with last Terrible version

### ISSUE THREAD

**Issue by alegrey91** [89luca89/terrible#71]

**Comment by 89luca89** [comment]
We could create a pipelineto release a new image on dockerhub each tag release, what do you think?
@alegrey91 @J4CKR3D

**Comment by alegrey91** [comment]
> We could create a pipelineto release a new image on dockerhub each tag release, what do you think?
> @alegrey91 @J4CKR3D

Dear @89luca89 ,
luckily for us, I've already created this using a github action.
This was the PR: https://github.com/89luca89/terrible/pull/56/files

**Comment by alegrey91** [comment]
Anyway we could add the current release variable to add the image tag the the docker image

**Comment by 89luca89** [comment]
We should then improve on that using 

`docker build --build-arg var_name=${VARIABLE_NAME} (...)`

and 

`${GITHUB_REF##*/}` or `$(echo $GITHUB_REF | cut -d / -f 3)`

for the tag version, so this process of updating the terrible version is automated

what do you think?

**Comment by alegrey91** [comment]
It's a good idea
