### ISSUE TITLE
[IMPROVEMENT] Security updates should not be enforced

### ISSUE THREAD

**Issue by 89luca89** [89luca89/terrible#86]
Security updates should be optional or delegated to terrible_custom_provisioner

this comes handy in situations where no internet is available or to keep track of package versions.

It could be just removed and be a part of `terrible_custom_provisioners` and left to the user

**Comment by alegrey91** [comment]
We could create the variable `security_updates` to enable them on the inventory.
Basically, the variable is set to `false` by default and in case you want to apply the security updates, just add `security_updates: true` in your inventory (on each machine and/or group you want).
